[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

# Redirections pour Next.js
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/training"
  to = "/training.html"
  status = 200

[[redirects]]
  from = "/book"
  to = "/book.html"
  status = 200

[[redirects]]
  from = "/videos"
  to = "/videos.html"
  status = 200

[[redirects]]
  from = "/music"
  to = "/music.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

# Redirection catch-all pour le SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.{js,css,png,jpg,jpeg,svg,ico,woff,woff2,ttf,eot,otf,mp4,webm,ogg,mp3,wav,flac,aac,m4a,webp,gif,pdf}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 